### ISSUE TITLE
Transaction not confirmed for so many days

### ISSUE THREAD

**Issue by sathish11test** [iotaledger/iota.lib.js#222] opened 2018-05-23 07:29 UTC
### Transaction is Pending
I have make the transaction and I got the response properly, but the transaction is still pending for so many days.

Coding:
`const seed = '---'; // For security purpose I have removed here`
`const addr = 'OWYVSTODUHKXKQKVHCDHGRNRCGNEUREWWTDPDRDBJPPJXXWIGTFXZDEMICJHAZEMMGPJKNIVLMOPNBKRXCSWKWFTZX';`
`const transfers = [`
`  {`
`    value: 1300000,`
`    address: addr`
`  }`
`];`
`var options = [];`
`iota.api.sendTransfer(seed, 3, 14, transfers, options, (error, success) => {`
`  if (error) {`
`    console.log(error);`
`  } else {`
`    console.log(success);`
`  }`
`});`

Kindly help me to solve this problem.

**Comment by chrisdukakis** [comment] 2018-05-23 08:26
Hi @sathish11test ,
you can use `replayBundle(tailHash, 3, 14)`, where `tailHash` is `hash` of pending transaction with `currentIndex=0`. You can replay (also referred to as _reattach_ ) the bundle as many times as needed, and eventually one reattachment will be confirmed, as long as there is sufficient balance on your input addresses and bundle is valid.

I'm closing this because it's not related to a library problem.

Feel free to join [IOTA on Discord](https://discord.gg/paVtQtq) and ask questions like this in #javascript and other developer channels. There are many skilled community members willing to help!

**Closed by chrisdukakis** 2018-05-23 08:26 UTC
Labels: question
