### ISSUE TITLE
promoteTransaction query

### ISSUE THREAD

**Issue by ibexes** [iotaledger/iota.lib.js#144] opened 2017-12-22 22:33 UTC
In the readme doc it's `iota.api.promoteTransaction(depth, minWeightMagnitude, transfers [, params], callback)`, but according to line 644 in lib/api/api.js, it should be `(tail, depth, minWeightMagnitude, transfer, params, callback)` where tail is tx index 0.

Also, what exactly is transfer? Is that just the bundle hash? If it is then can we just eliminate the need to also pass in tail and just get it from the bundle?

tdlr: what is 'transfer'.

**Comment by felhe** [comment] 2017-12-23 16:33
I already opened a pull request to fix the doc (see #142).
As you spam transactions on top of your unconfirmed transaction, you use the same transfer object which is required for [sendTransfer()](https://github.com/iotaledger/iota.lib.js#sendtransfer):

 **`transfers`**: `Array` of transfer objects:
+  - **`address`**: `String` 81-tryte encoded address of recipient
+  - **`value`**: `Int` value to be transferred.
+  - **`message`**: `String` tryte-encoded message to be included in the bundle.
+  - **`tag`**: `String` 27-tryte encoded tag.

It doesn't matter which address you use in the transfer object.
Note that transfers is an array of transfer objects!

**Comment by ibexes** [comment] 2017-12-23 23:56
Thanks, I figured to just use `[{ address: '9'.repeat(81), value: 0, message: '', tag: '' }]` after dissecting the official wallet. 

I can't seem to figure out the purpose of 'isPromotable(tail)' - also called within the promoteTransaction method, every tail tx I give it always returns true, and if it's not tail, then I get a type error. Is that what was intended? Should confirmed bundles also be promotable? I feel like what it currently does is just tell you whether it is a tail tx or not, kinda counter-intuitive...

**Comment by chrisdukakis** [comment] 2018-04-08 16:08
@ibexes sorry for late response. `isPromotable(tail)` lets you know if a tail transaction is promotable. If not, it requires reattachment. It works only on tails. If transaction is confirmed you don't need to reattach or promote it.

I'll have to double check what's the response for confirmed transactions. If it's `true` then `isPromotable()` isn't good name because it prompts you to promote when not needed.

Readme has been updated with #142.

**Comment by chrisdukakis** [comment] 2018-07-06 00:16
Closing as documentation was updated. 
@ibexes as of `v1.0.0`, `isPromotable()` can return `true` for confirmed tails. Eventually it will return `false` after a while: https://github.com/iotaledger/iota.lib.js/tree/next/packages/core#example-with-checkconsistency--ispromotable
I'll open a separate issue for that in due time. That should deal with properly streamlining transaction issuance, confirmation checks, promotion and reattachments together.

**Closed by chrisdukakis** 2018-07-06 00:16 UTC
Labels: Documentation, L - Assigned
