### ISSUE TITLE
makeRequest.js "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by minyc510** [iotaledger/iota.lib.js#217] opened 2018-05-17 22:10 UTC
### Bug description
I'm using the iota.lib.js API's "getNewAddress" (and no other functions). 
It's within a create-react-app application and when i type in `npm start` I get the following errors on the terminal:
```
./node_modules/iota.lib.js/lib/utils/makeRequest.js
10:16-46 Critical dependency: the request of a dependency is an expression
```

The only instance of the js API is in one file, like so:
```
import IOTA from '../node_modules/iota.lib.js/lib/iota.js';
...
// Create IOTA instance with host and port as provider
      var iota = new IOTA({
      'host': 'http://localhost',
      'port': 14265
      });
      ...
      // Generate Address
      iota.api.getNewAddress(seed, options, (e, add) => {
        var newAdd = add[0];
        this.setState({address: newAdd});
      });

```
### Steps To Reproduce
1. `git clone https://github.com/minyc510/IOTA-Cold-Storage.git`
2. `cd IOTA-Cold-Storage`
3. `npm install`
4. `npm start`

**Comment by chrisdukakis** [comment] 2018-05-17 22:37
Duplicate of https://github.com/iotaledger/iota.lib.js/issues/158
Let's move this to 158.

**Closed by chrisdukakis** 2018-05-17 22:37 UTC
Labels: duplicate
